### ISSUE TITLE
Application breaks on attribute error

### ISSUE THREAD

**Issue by mmerklinger** [Nitrokey/nitrokey-app2#109]
Current `main` branch breaks with following error.

```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/Projects/nitrokey-app2/nitrokeyapp/__main__.py", line 40, in <module>
    main()
  File "/home/user/Projects/nitrokey-app2/nitrokeyapp/__main__.py", line 34, in main
    window = GUI(app, log_file)
  File "/home/user/Projects/nitrokey-app2/venv/lib64/python3.9/site-packages/nitrokeyapp/gui.py", line 121, in __init__
    self.views: list[DeviceView] = [self.overview_tab, SecretsTab(self)]
  File "/home/user/Projects/nitrokey-app2/venv/lib64/python3.9/site-packages/nitrokeyapp/secrets_tab/__init__.py", line 78, in __init__
    self.reset()
  File "/home/user/Projects/nitrokey-app2/venv/lib64/python3.9/site-packages/nitrokeyapp/secrets_tab/__init__.py", line 96, in reset
    self.reset_ui()
  File "/home/user/Projects/nitrokey-app2/venv/lib64/python3.9/site-packages/nitrokeyapp/secrets_tab/__init__.py", line 104, in reset_ui
    self.hide_otp()
  File "/home/user/Projects/nitrokey-app2/venv/lib64/python3.9/site-packages/nitrokeyapp/secrets_tab/__init__.py", line 227, in hide_otp
    self.ui.lineEditOtp.hide()
AttributeError: 'Ui_SecretsTab' object has no attribute 'lineEditOtp'
```

**Comment by robin-nitrokey** [comment]
Did you run `make build-ui`?

**Comment by mmerklinger** [comment]
You are right. I forgot about this.
