### ISSUE TITLE
[NK3][Secrets][Totp] Deleting Pin-Protected TOTP Secret in App Fails

### ISSUE THREAD

**Issue by jornfranke** [Nitrokey/nitrokey-app2#133]
Hi,
I created a pin-protected TOTP Secret on my NK3 using the app. I can use the secret and it generates successfully correct TOTP tokens. I now want to delete the secret from the app, but it fails
```
Traceback (most recent call last):
  File "nitrokeyapp/secrets_tab/worker.py", line 365, in delete_credential
  File "nitrokeyapp/worker.py", line 64, in run
  File "nitrokeyapp/secrets_tab/worker.py", line 233, in run
  File "pynitrokey/nk3/secrets_app.py", line 497, in delete
  File "pynitrokey/nk3/secrets_app.py", line 341, in _send_receive
  File "pynitrokey/nk3/secrets_app.py", line 384, in _send_receive_inner
pynitrokey.nk3.secrets_app.SecretsAppException: SecretsAppException(code=6a82/NotFound)```

I can delete it from the command line successfully
```
nitropy nk3 secrets remove <SECRET_NAME>
```

**Comment by robin-nitrokey** [comment]
Thanks for the report!  Indeed, we should query the PIN and verify it before trying to delete a PIN-protected credential.

https://github.com/Nitrokey/nitrokey-app2/blob/d6e78e6625e22d74c56dde73030d0b370c986454/nitrokeyapp/secrets_tab/worker.py#L229-L234

Similar to what we already do when generating the OTP:

https://github.com/Nitrokey/nitrokey-app2/blob/d6e78e6625e22d74c56dde73030d0b370c986454/nitrokeyapp/secrets_tab/worker.py#L258-L264
