### ISSUE TITLE
No module named 'nitrokeyapp.logger'

### ISSUE THREAD

**Issue by pescepalla** [Nitrokey/nitrokey-app2#216]
I'm getting a ModuleNotFoundError while launching the nitrokeyapp2:

```
Traceback (most recent call last):
  File "/usr/bin/nitrokeyapp", line 5, in <module>
    from nitrokeyapp.__main__ import main
  File "/usr/lib/python3.11/site-packages/nitrokeyapp/__main__.py", line 10, in <module>
    from nitrokeyapp.gui import GUI
  File "/usr/lib/python3.11/site-packages/nitrokeyapp/gui.py", line 20, in <module>
    from nitrokeyapp.error_dialog import ErrorDialog
  File "/usr/lib/python3.11/site-packages/nitrokeyapp/error_dialog.py", line 8, in <module>
    from nitrokeyapp.logger import save_log
ModuleNotFoundError: No module named 'nitrokeyapp.logger'
``` 

OS: Arch Linux
NKApp2 version: 2.2.1

**Comment by daringer** [comment]
can you share how you installed it ? 
overall that's kind of weird as the file "should" be there: https://github.com/Nitrokey/nitrokey-app2/blob/main/nitrokeyapp/logger.py

**Comment by pescepalla** [comment]
From here: https://aur.archlinux.org/packages/nitrokey-app2

**Comment by pescepalla** [comment]
Manually copying the `logger.py` file in the `/usr/lib/python3.11/site-packages/nitrokeyapp` directory solves the issue. Is it maybe a packaging issue?
