### ISSUE TITLE
Cannot launch flatpak app on Debian 11 Bullseye

### ISSUE THREAD

**Issue by e-alfred** [Nitrokey/nitrokey-app2#231]
Hello,

I installed the Nitrokey App 2.2.1 on Debian Bullseye using Flatpak 1.10.8, but starting it only gives the following error message:

> $ flatpak run com.nitrokey.nitrokey-app2
Traceback (most recent call last):
  File "/app/bin/nitrokeyapp", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/nitrokeyapp/__main__.py", line 34, in main
    window = GUI(app, log_file)
             ^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/nitrokeyapp/gui.py", line 182, in __init__
    self.init_gui()
  File "/app/lib/python3.11/site-packages/nitrokeyapp/gui.py", line 334, in init_gui
    self.detect_added_devices()
  File "/app/lib/python3.11/site-packages/nitrokeyapp/gui.py", line 233, in detect_added_devices
    self.toggle_update_btn()
  File "/app/lib/python3.11/site-packages/nitrokeyapp/gui.py", line 211, in toggle_update_btn
    self.overview_tab.set_update_enabled(device_count == 1)
  File "/app/lib/python3.11/site-packages/nitrokeyapp/overview_tab.py", line 120, in set_update_enabled
    self.disable_update_nrf()
  File "/app/lib/python3.11/site-packages/nitrokeyapp/overview_tab.py", line 51, in disable_update_nrf
    if IS_FLATHUB and self.data.status.variant.name == "NRF52":
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
QThread: Destroyed while thread is still running

**Comment by daringer** [comment]
uh, I think we've seen this before, this is a bug due to an older Nitrokey 3 firmware version - can you please use `nitropy nk3 update` to run a firmware update on the device ? afterwards it should work... https://docs.nitrokey.com/software/nitropy/all-platforms/installation#pipx

**Comment by e-alfred** [comment]
I fixed it myself by installing Flatpak 1.14 instead of 1.10 and the app works now. Is there a minimal requirement for a Flatpak version for the app?

**Comment by daringer** [comment]
We are now aware of such a version restriction - but if this works for you it is for sure something to keep in mind - even though the error you reported is quite surely not related to flathub itself I would guess, but who knows ... Can you confirm that you did not update the nk3 firmware using another tool (pynitrokey) in between ?
