### ISSUE TITLE
[Arch Linux] Nitrokey App 2 fails to start

### ISSUE THREAD

**Issue by klakomuc** [Nitrokey/nitrokey-app2#267]
Hi,

the Nitrokey App 2 fails to start on Arch Linux (Linux archie 6.10.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000 x86_64 GNU/Linux). Trying to start it from GNOME Terminal results in:

```
/usr/lib/python3.12/site-packages/google/protobuf/internal/api_implementation.py:89: UserWarning: Selected implementation cpp is not available.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/bin/nitrokeyapp", line 5, in <module>
    from nitrokeyapp.__main__ import main
  File "/usr/lib/python3.12/site-packages/nitrokeyapp/__main__.py", line 10, in <module>
    from nitrokeyapp.gui import GUI
  File "/usr/lib/python3.12/site-packages/nitrokeyapp/gui.py", line 14, in <module>
    from nitrokeyapp.device_data import DeviceData
  File "/usr/lib/python3.12/site-packages/nitrokeyapp/device_data.py", line 4, in <module>
    from pynitrokey import nk3
  File "/usr/lib/python3.12/site-packages/pynitrokey/nk3/__init__.py", line 14, in <module>
    from pynitrokey.trussed.bootloader.nrf52 import SignatureKey
  File "/usr/lib/python3.12/site-packages/pynitrokey/trussed/bootloader/nrf52.py", line 29, in <module>
    from .nrf52_upload.dfu.init_packet_pb import InitPacketPB
  File "/usr/lib/python3.12/site-packages/pynitrokey/trussed/bootloader/nrf52_upload/dfu/init_packet_pb.py", line 39, in <module>
    from . import dfu_cc_pb2 as pb
  File "/usr/lib/python3.12/site-packages/pynitrokey/trussed/bootloader/nrf52_upload/dfu/dfu_cc_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/lib/python3.12/site-packages/google/protobuf/descriptor.py", line 28, in <module>
    from google.protobuf.pyext import _message
ImportError: libabsl_die_if_null.so.2401.0.0: cannot open shared object file: No such file or directory
```

Best regards
klakomuc

**Comment by daringer** [comment]
this is a pynitrokey issue, closing and handling in: https://github.com/Nitrokey/pynitrokey/issues/562#issuecomment-2311946085
