### ISSUE TITLE
Flatpak does not work on Ubuntu 24.04

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nitrokey-app2#316]
From the Nitrokey Matrix channel:

```
$ flatpak run com.nitrokey.nitrokey-app2
Traceback (most recent call last):
  File "/app/bin/nitrokeyapp", line 5, in <module>
    from nitrokeyapp.__main__ import main
  File "/app/lib/python3.12/site-packages/nitrokeyapp/__main__.py", line 6, in <module>
    from PySide6 import QtWidgets
ImportError: could not import module 'PySide6.QtGui'

$ flatpak info com.nitrokey.nitrokey-app2

Nitrokey App2 - Manage your Nitrokey 3 device

          ID: com.nitrokey.nitrokey-app2
         Ref: app/com.nitrokey.nitrokey-app2/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.3.3
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 188,9 MB
     Runtime: org.kde.Platform/x86_64/6.8
         Sdk: org.kde.Sdk/x86_64/6.8

      Commit: 4b8ea658efbae77c5a76c4255e8af0554a69fe955f034982380a527d4cc002f5
      Parent: 8d8cc88ae659662ddb2bad2a9d3505a8b6deadbeeb943c6da3e98f47e4e28ae2
     Subject: bump to version v2.3.3 (a1576898)
        Date: 2024-11-21 08:55:07 +0000
```

**Comment by schildbach** [comment]
I'm the one who reported it on the Matrix channel. I just tried the following:

`flatpak uninstall --all` to remove all apps and flatpak deps I already had installed.

`flatpak list` is empty.

Then:

```
$ flatpak install flathub com.nitrokey.nitrokey-app2
Looking for matches…
Required runtime for com.nitrokey.nitrokey-app2/x86_64/stable (runtime/org.kde.Platform/x86_64/6.8) found in remote flathub
Do you want to install it? [Y/n]: y

com.nitrokey.nitrokey-app2 permissions:
    ipc                   network       fallback-x11       wayland      x11      devices      file access [1]
    dbus access [2]

    [1] xdg-config/kdeglobals:ro
    [2] com.canonical.AppMenu.Registrar, org.kde.KGlobalSettings, org.kde.kconfig.notify


        ID                                              Branch                Op            Remote             Download
 1. [✓] org.freedesktop.Platform.GL.default             24.08                 i             flathub            146,5 MB / 146,8 MB
 2. [✓] org.freedesktop.Platform.GL.default             24.08extra            i             flathub             22,7 MB / 146,8 MB
 3. [✓] org.freedesktop.Platform.VAAPI.Intel            24.08                 i             flathub             14,4 MB / 14,5 MB
 4. [✓] org.freedesktop.Platform.openh264               2.4.1                 i             flathub            920,7 kB / 976,5 kB
 5. [✓] org.gtk.Gtk3theme.Yaru                          3.22                  i             flathub            139,3 kB / 191,5 kB
 6. [✓] org.kde.Platform.Locale                         6.8                   i             flathub             18,6 kB / 400,4 MB
 7. [✓] org.kde.Platform                                6.8                   i             flathub            298,5 MB / 370,7 MB
 8. [✓] com.nitrokey.nitrokey-app2                      stable                i             flathub             51,3 MB / 62,0 MB

Installation complete.
```

But same issue as above:

```
$ flatpak run com.nitrokey.nitrokey-app2
Traceback (most recent call last):
  File "/app/bin/nitrokeyapp", line 5, in <module>
    from nitrokeyapp.__main__ import main
  File "/app/lib/python3.12/site-packages/nitrokeyapp/__main__.py", line 6, in <module>
    from PySide6 import QtWidgets
ImportError: could not import module 'PySide6.QtGui'
```

It's the Ubuntu 24.04 version of flatpak: `1.14.6-1ubuntu0.1`

**Comment by daringer** [comment]
oh wow - this is special ... isn't this the purpose of flatpak to not have these issues .... Maybe it's due to me too aggressively [cleaning up qt inside the flatpak](https://github.com/flathub/com.nitrokey.nitrokey-app2/blob/master/com.nitrokey.nitrokey-app2.yml#L19) - but this would mean that flatpak would use my system's Qt/PySide instead, which is again not how I understand flatpak should work...

@schildbach do you have Pyside 6.* installed on your host system ?

**Comment by schildbach** [comment]
> @schildbach do you have Pyside 6.* installed on your host system ?

I assume no. I'm not familiar with Python, but here are the (un)installed packages with that name.

```
$ dpkg -l *pyside*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
un  libpyside2-py3 <none>       <none>       (no description available)
```

**Comment by sambonbonne** [comment]
Hello, I'm having the same issue on Aeon Desktop after installing the application with Flatpak (this is my first install).

Exact same error when running:

```sh
$ flatpak run --user com.nitrokey.nitrokey-app2                                                 
Traceback (most recent call last):
  File "/app/bin/nitrokeyapp", line 5, in <module>
    from nitrokeyapp.__main__ import main
  File "/app/lib/python3.12/site-packages/nitrokeyapp/__main__.py", line 6, in <module>
    from PySide6 import QtWidgets
ImportError: could not import module 'PySide6.QtGui
```

**Comment by hfjkd73** [comment]
Can confirm. Tried to install the flatpak just yesterday. Same from 
```
PySide6 import QtWidgets
ImportError: could not import module 'PySide6.QtGui
```
message on Linux Mint 22 and Fedora Bluefin.

**Comment by christian-hnz** [comment]
Having the same issue on ubuntu 24.04. Just downgraded to 2.3.2
```
flatpak update --commit=8d8cc88ae659662ddb2bad2a9d3505a8b6deadbeeb943c6da3e98f47e4e28ae2 com.nitrokey.nitrokey-app2
```
and this works flawlessly.

**Comment by romainreignier** [comment]
Same issue on Ubuntu 20.04 it seems to be a Flatpak packaging issue so whatever distribution or OS version used, the issue will be there I guess.

**Comment by daringer** [comment]
ok, thanks for all the inputs - seems like flathub accepted the build, but now the very same fails - we updated it [here](https://github.com/flathub/com.nitrokey.nitrokey-app2/pull/4) .....

you can try: 
```
flatpak install --user https://dl.flathub.org/build-repo/150003/com.nitrokey.nitrokey-app2.flatpakref
```

or just wait some time, then update the version through flathub directly

**Comment by daringer** [comment]
The build is not published on flathub: https://flathub.org/de/apps/com.nitrokey.nitrokey-app2
closing this issue as we cannot see the same behavior as reported anymore - feel free to re-open if it still occurs to you

**Comment by christian-hnz** [comment]
Just updated and everything is fine. Thanks for the fixing!
