### ISSUE TITLE
If CTAP communication is corrupted nitrokey-app2 will not start

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitrokey-app2#38]
(using the single binary linux version)

This is likely a rare case for the end-user, but a busy ctap channel can easily occur during development. The actual issue to solve here is to move the communication with the device into a separate thread to ensure that any errors during communication does not crash the entire app.

example output (directly after starting):
```
Traceback (most recent call last):
  File "nitrokeyapp/__main__.py", line 20, in <module>
  File "nitrokeyapp/__main__.py", line 16, in main
  File "nitrokeyapp/gui.py", line 149, in __init__
  File "nitrokeyapp/gui.py", line 290, in init_gui
  File "nitrokeyapp/gui.py", line 202, in detect_nk3
  File "pynitrokey/nk3/__init__.py", line 25, in list
  File "pynitrokey/nk3/device.py", line 146, in list
  File "pynitrokey/nk3/device.py", line 73, in __init__
  File "pynitrokey/nk3/admin_app.py", line 71, in status
  File "pynitrokey/nk3/admin_app.py", line 58, in _call
  File "pynitrokey/nk3/device.py", line 133, in _call
  File "fido2/hid/__init__.py", line 216, in call
fido2.ctap.CtapError: CTAP error: 0x06 - CHANNEL_BUSY
[1924370] Failed to execute script '__main__' due to unhandled exception!

```

**Comment by daringer** [comment]
would be solved by #94 - closing
