### ISSUE TITLE
ImportError: cannot import name 'main' from 'nitrokeyapp'

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nitrokey-app2#55]
Reproducer 1:
```
$ make update-venv
$ ./venv/bin/nitrokeyapp 
Traceback (most recent call last):
  File "/home/robin/reps/nitrokey-app2/./venv/bin/nitrokeyapp", line 5, in <module>
    from nitrokeyapp import main
ImportError: cannot import name 'main' from 'nitrokeyapp' (/home/robin/reps/nitrokey-app2/venv/lib/python3.9/site-packages/nitrokeyapp/__init__.py)
```

Reproducer 2:
```
$ pipx install git+https://github.com/Nitrokey/nitrokey-app2
$ nitrokeyapp 
Traceback (most recent call last):
  File "/home/robin/.local/bin/nitrokeyapp", line 5, in <module>
    from nitrokeyapp import main
ImportError: cannot import name 'main' from 'nitrokeyapp' (/home/robin/.local/pipx/venvs/nitrokeyapp/lib/python3.9/site-packages/nitrokeyapp/__init__.py)
```

**Comment by PureTryOut** [comment]
Can reproduce and the proposed PR fixes the issue. However then something new comes up:

```
$ nitrokeyapp
Traceback (most recent call last):
  File "/usr/bin/nitrokeyapp", line 5, in <module>
    from nitrokeyapp.__main__ import main
  File "/usr/lib/python3.11/site-packages/nitrokeyapp/__main__.py", line 5, in <module>
    import nitrokeyapp.ui.resources_rc  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'nitrokeyapp.ui.resources_rc'
```

`/usr/lib/python3.11/site-packages/nitrokeyapp/ui/resources.qrc` exists but indeed no `/usr/lib/python3.11/site-packages/nitrokeyapp/ui/resources_rc`.

Does no one actually run this application? :sweat_smile:
