### ISSUE TITLE
Does not work on MacOS X 12.6.3 Monterey - ModuleNotFoundError: No module named 'nitrokeyapp.ui.resources_rc' 

### ISSUE THREAD

**Issue by arnotron** [Nitrokey/nitrokey-app2#62]
Installation according to the instructions on MacOS X 12.6.3 Monterey does not work. Is this a known issue or expected?

I get the following error message:

(venv) xxxx@xxxx nitrokey-app2 % nitrokeyapp
Traceback (most recent call last):
  File "/Users/xxxx/src/nitrokey-app2/venv/bin/nitrokeyapp", line 5, in <module>
    from nitrokeyapp.__main__ import main
  File "/Users/xxxx/src/nitrokey-app2/venv/lib/python3.9/site-packages/nitrokeyapp/__main__.py", line 5, in <module>
    import nitrokeyapp.ui.resources_rc  # noqa: F401
ModuleNotFoundError: No module named 'nitrokeyapp.ui.resources_rc'

% nitropy version
Command line tool to interact with Nitrokey devices 0.4.35
0.4.35

% python --version
Python 3.9.6

% uname -a
Darwin xxxx 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64

**Comment by arnotron** [comment]
Indeed, you were right. I failed to see the error message. It showed:

Untracked or deleted files in the source directory. Commit, undo or ignore these files in your VCS

Trying a git commit, I was told about an untracked file named .DS_Store, which is a hidden MacOS file for metadata. Adding this to .gitignore made the build work, so I am closing this issue. Thanks for pushing me in the right direction.
